import { getServerSession } from 'next-auth';
import { options as authOptions } from '@/app/api/auth/[...nextauth]/options';
import { readNemtAdminState } from '@/server/nemt-admin-store';
import { sendEmail } from '@/server/email-service';
import { readGeniusPayoutRunById } from '@/server/genius-store';

const ALLOWED_GENIUS_USER_IDS = new Set(['user-16', 'user-20']);

const assertGeniusAdmin = userId => {
  if (!ALLOWED_GENIUS_USER_IDS.has(String(userId || '').trim())) {
    throw new Error('Forbidden');
  }
};

const getDriverEmailFromAdminState = async driverId => {
  const adminState = await readNemtAdminState();
  const drivers = Array.isArray(adminState?.drivers) ? adminState.drivers : [];
  const driver = drivers.find(row => String(row?.id || '').trim() === String(driverId || '').trim());
  if (!driver) return { email: '', name: 'Driver' };
  const email = String(driver?.portalEmail || driver?.email || '').trim();
  const name = String(driver?.displayName || driver?.name || `${driver?.firstName || ''} ${driver?.lastName || ''}` || 'Driver').trim() || 'Driver';
  return { email, name };
};

const buildPayoutEmail = ({ payout, driverName }) => {
  const subject = `Payout Receipt ${payout.serviceDate} | ${driverName}`;
  const html = `
    <div style="font-family: Arial, sans-serif; color: #111827;">
      <h2 style="margin-bottom: 6px;">Payout Receipt</h2>
      <p style="margin-top: 0; color: #6b7280;">Generated by Genius Billing</p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 12px 0;" />
      <p><strong>Driver:</strong> ${driverName}</p>
      <p><strong>Service Date:</strong> ${payout.serviceDate || '-'}</p>
      <p><strong>Trips:</strong> ${payout.tripCount || 0}</p>
      <p><strong>LOS (W/A/STR):</strong> ${payout.wheelchairCount || 0}/${payout.ambulatoryCount || 0}/${payout.stretcherCount || 0}</p>
      <p><strong>Gross Amount:</strong> $${Number(payout.grossAmount || 0).toFixed(2)}</p>
      <p><strong>Fuel Receipts:</strong> ${payout.fuelReceiptCount || 0}</p>
      <p><strong>Fuel Total:</strong> $${Number(payout.fuelTotal || 0).toFixed(2)}</p>
      <p><strong>Fuel Reimbursement:</strong> ${payout.reimburseAllowed ? 'Unlocked' : 'Locked'}</p>
      <p><strong>Receipt ID:</strong> ${payout.id}</p>
      <p><strong>Created At:</strong> ${payout.createdAt || '-'}</p>
    </div>
  `;

  const text = [
    'Payout Receipt',
    `Driver: ${driverName}`,
    `Service Date: ${payout.serviceDate || '-'}`,
    `Trips: ${payout.tripCount || 0}`,
    `LOS (W/A/STR): ${payout.wheelchairCount || 0}/${payout.ambulatoryCount || 0}/${payout.stretcherCount || 0}`,
    `Gross Amount: $${Number(payout.grossAmount || 0).toFixed(2)}`,
    `Fuel Receipts: ${payout.fuelReceiptCount || 0}`,
    `Fuel Total: $${Number(payout.fuelTotal || 0).toFixed(2)}`,
    `Fuel Reimbursement: ${payout.reimburseAllowed ? 'Unlocked' : 'Locked'}`,
    `Receipt ID: ${payout.id}`,
    `Created At: ${payout.createdAt || '-'}`
  ].join('\n');

  return { subject, html, text };
};

export async function POST(req) {
  try {
    const session = await getServerSession(authOptions);
    const userId = String(session?.user?.id || '').trim();
    if (!userId) {
      return Response.json({ success: false, error: 'Authentication required' }, { status: 401 });
    }

    assertGeniusAdmin(userId);

    const body = await req.json().catch(() => ({}));
    const payoutId = String(body?.payoutId || '').trim();
    if (!payoutId) {
      return Response.json({ success: false, error: 'payoutId is required' }, { status: 400 });
    }

    const payout = await readGeniusPayoutRunById(payoutId);
    if (!payout) {
      return Response.json({ success: false, error: 'Payout receipt not found' }, { status: 404 });
    }

    const driverInfo = await getDriverEmailFromAdminState(payout.driverId);
    const toEmail = String(body?.toEmail || driverInfo.email || '').trim();
    if (!toEmail) {
      return Response.json({ success: false, error: 'Driver email is missing' }, { status: 400 });
    }

    const { subject, html, text } = buildPayoutEmail({ payout, driverName: driverInfo.name });
    const emailResult = await sendEmail({ to: toEmail, subject, html, text });

    if (!emailResult.success) {
      if (emailResult.reason === 'SMTP_NOT_CONFIGURED') {
        return Response.json({ success: false, error: 'SMTP not configured. Add SMTP settings first.' }, { status: 500 });
      }
      return Response.json({ success: false, error: emailResult.reason || 'Unable to send email' }, { status: 500 });
    }

    return Response.json({ success: true, messageId: emailResult.messageId, sentTo: toEmail });
  } catch (error) {
    const status = String(error?.message || '').toLowerCase() === 'forbidden' ? 403 : 500;
    return Response.json({ success: false, error: status === 403 ? 'Forbidden' : error?.message || 'Unable to send payout receipt email' }, { status });
  }
}
